# Site settings
title: Blog del equipo de coches.com
email: tekis@coches.com
description: > # this means to ignore newlines until "baseurl:"
 Este es el blog del equipo de coches.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://labs.coches.com" # the base hostname & protocol for your site
twitter_handle: '@cochescomlab'
disqus: cochescomlab

#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/fondoHomeCoches.jpg"
paginate:	5


# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/cochescomlab
    desc: SÃ­guenos en twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/coches
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

